# Generated by Django 5.0.6 on 2024-06-03 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SortVision", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kraj",
            name="w_finale",
        ),
    ]
