# Generated by Django 5.0.6 on 2024-06-03 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SortVision", "0002_remove_kraj_w_finale"),
    ]

    operations = [
        migrations.AddField(
            model_name="kraj",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kraj",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
