# Generated by Django 5.0.6 on 2024-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SortVision", "0004_kraj_zdjecie"),
    ]

    operations = [
        migrations.AddField(
            model_name="kraj",
            name="zdjecie_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kraj",
            name="zdjecie_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kraj",
            name="zdjecie",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
