# Generated by Django 5.0.6 on 2024-06-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SortVision", "0005_kraj_zdjecie_height_kraj_zdjecie_width_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kraj",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="kraj",
            name="publish_date",
        ),
        migrations.RemoveField(
            model_name="polfinal",
            name="kraje",
        ),
        migrations.RemoveField(
            model_name="polfinal",
            name="numer",
        ),
        migrations.AddField(
            model_name="polfinal",
            name="kraj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SortVision.kraj",
            ),
        ),
        migrations.AddField(
            model_name="polfinal",
            name="polfinal",
            field=models.IntegerField(
                blank=True, choices=[(1, "Półfinał 1"), (2, "Półfinał 2")], null=True
            ),
        ),
    ]
